apiVersion: v1
kind: Secret
metadata:
  name: nm-config
type: Opaque
stringData:
  config.ini: |
    {{ .Values.config.algorithm }}
    wallet: {{ .Values.config.wallet }}
    email: {{ .Values.config.email }}